source 'https://github.com/CocoaPods/Specs'
source 'https://cdn.cocoapods.org/'
platform :ios, '11.0'

target 'UnityFramework' do
  pod 'Google-Mobile-Ads-SDK', '~> 9.0'
end
target 'Unity-iPhone' do
end
use_frameworks! :linkage => :static
